# config folder
config:
    root: config/
    xml: robin.xml              # codesys source xml
    types: types.yml            # data types map
    templates: templates.yml    # templates

# package folders
package:
    root: ../../
    node: src/
    insts: src/robin/
    msg: msg/
    structs: include/robin/
    cmakelists: CMakeLists.txt
    package_xml: package.xml

# source file names
src_files:
    node: robin_node.cpp
    insts: robin_inst.cpp  #TODO change to robin_insts.cpp
    structs: structs.h
